package model;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CommitInfo.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class CommitInfo extends LogInfo {
	private String description;//diff content
	private String title;//commit Title
	private String originFileDescriptioin;// file content version...(before commit!!)
	public CommitInfo() {
		super();
	}
	public CommitInfo(String code, String objectCode, String kind, String content,
			String date, String memberCode, boolean merge,String title) {
		super(code,objectCode,kind,content,date,memberCode,merge);
		this.title = title;
	}
	public CommitInfo(String code, String objectCode, String kind, String content,
			String date, String memberCode, boolean merge,String description, String title,String originFileDescriptioin) {
		super(code,objectCode,kind,content,date,memberCode,merge);
		this.description = description;
		this.title = title;
		this.originFileDescriptioin = originFileDescriptioin;
	}
	
	public CommitInfo(String objectCode, String kind, String content,
			String date, String memberCode, boolean merge,String title) {
		super(objectCode,kind,content,date,memberCode,merge);
		this.title = title;
	}
	public CommitInfo(String objectCode, String kind, String content,
			String date, String memberCode, boolean merge,String description, String title) {
		super(objectCode,kind,content,date,memberCode,merge);
		this.description = description;
		this.title = title;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getOriginFileDescriptioin() {
		return originFileDescriptioin;
	}
	public void setOriginFileDescriptioin(String originFileDescriptioin) {
		this.originFileDescriptioin = originFileDescriptioin;
	}
	
}
