package model;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OriginFile.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class MyOriginFile extends File {
	
	private String type;
	private String code;
	private String name;
	private String path;
	private List<String> childFolderList;
	private List<String> childFileList;
	
	public MyOriginFile(String path,String type) {
		super(path);
		this.path = path;
		this.type= type;
		this.childFolderList  = new ArrayList<String>();
		this.childFileList  = new ArrayList<String>();
	}
	
	public MyOriginFile(String code,String path,String type) {
		super(path);
		this.code = code;
		this.path = path;
		this.type = type;
		this.childFolderList  = new ArrayList<String>();
		this.childFileList  = new ArrayList<String>();
	}
	
	public MyOriginFile(String code, String name, String path,String type) {
		super(path);
		this.code = code;
		this.name = name;
		this.path = path;
		this.childFolderList  = new ArrayList<String>();
		this.childFileList  = new ArrayList<String>();
		this.type = type;
	}
	
	
////////////////////////////////////////////////////////////////////////////////////////////
	
	
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPath() {
		return path;
	}
	public void setPath(String path) {
		this.path = path;
	}
	
	public List<String> getChildFolderList() {
		return childFolderList;
	}

	public void setChildFolderList(List<String> childFolderList) {
		this.childFolderList = childFolderList;
	}

	public String getType(){
		return this.type;
	}
	public boolean isDirectory(){
		if(this.type.equals("file"))return false;
		else return true;
	}
	public boolean isFile(){
		if(this.type.equals("file"))return true;
		else return false;
	}

	public List<String> getChildFileList() {
		return childFileList;
	}

	public void setChildFileList(List<String> childFileList) {
		this.childFileList = childFileList;
	}

}
