package model;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OriginFolder.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class OriginFolder extends File {
	
	private String code;
	private String name;
	private String description;
	private String path;
	private String makeDate;
	private String alterDate;
	private double size;
	private String parentFolder;
	private String parentFolderPath;
	private List<String> childFolderList;
	private List<String> childFileList;
	
	public OriginFolder(String path) {
		super(path);
		this.path=path;
		
		this.childFileList = new ArrayList<String>();
		this.childFolderList = new ArrayList<String>();
		this.size=0;
	}
	/*public OriginFolder(String path, String name, String description) {
		super(path);
		this.path=path;
		this.name = name;
		this.childFileList = new ArrayList<String>();
		this.childFolderList = new ArrayList<String>();
		this.size=0;
		this.description = description;
	}
	public OriginFolder(String path, String name, String description,String makeDate) {
		super(path);
		this.path=path;
		this.name = name;
		this.childFileList = new ArrayList<String>();
		this.childFolderList = new ArrayList<String>();
		this.size=0;
		this.description = description;
		this.makeDate = makeDate;
	}
	public OriginFolder(String path, String name, String description,String makeDate,String parentFolder) {
		super(path);
		this.path=path;
		this.name = name;
		this.childFileList = new ArrayList<String>();
		this.childFolderList = new ArrayList<String>();
		this.size=0;
		this.description = description;
		this.makeDate = makeDate;
		this.parentFolder = parentFolder;
	}
	public OriginFolder(String code,String path, String name, String description,String makeDate,String parentFolder) {
		super(path);
		this.code = code;
		this.path=path;
		this.name = name;
		this.childFileList = new ArrayList<String>();
		this.childFolderList = new ArrayList<String>();
		this.size=0;
		this.description = description;
		this.makeDate = makeDate;
		this.parentFolder = parentFolder;
	}*/
	public OriginFolder(String path, String name, String makeDate,String parentFolder) {
		super(path);
		this.name = name;
		this.path = path;
		this.makeDate = makeDate;
		this.parentFolder = parentFolder;
		this.size = 0;
	}
	public OriginFolder(String path, String name, String makeDate,
			String parentFolder, String description,int size) {
		super(path);
		this.name = name;
		this.path = path;
		this.makeDate = makeDate;
		this.parentFolder = parentFolder;
		this.description = description;
		this.size = size;
	}
	
	public OriginFolder(String code,String path, String name, String makeDate,String parentFolder) {
		super(path);
		this.code = code;
		this.name = name;
		this.path = path;
		this.makeDate = makeDate;
		this.parentFolder = parentFolder;
		this.size = 0;
	}
	public OriginFolder(String code,String path, String name, String makeDate,String parentFolder, String description,int size) {
		super(path);
		this.code = code;
		this.name = name;
		this.path = path;
		this.makeDate = makeDate;
		this.parentFolder = parentFolder;
		this.description = description;
		this.size = size;
	}
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getPath() {
		return path;
	}
	public void setPath(String path) {
		this.path = path;
	}
	
	public double getSize() {
		return size;
	}
	public void setSize(double size) {
		this.size = size;
	}
	public String getParentFolder() {
		return parentFolder;
	}
	public void setParentFolder(String parentFolder) {
		this.parentFolder = parentFolder;
	}
	public List<String> getChildFolderList() {
		return childFolderList;
	}
	public void setChildFolderList(List<String> childFolderList) {
		this.childFolderList = childFolderList;
	}
	public List<String> getChildFileList() {
		return childFileList;
	}
	public void setChildFileList(List<String> childFileList) {
		this.childFileList = childFileList;
	}
	public String getParentFolderPath() {
		if(parentFolderPath == null){
			System.out.println(this.path+"   "+this.name);
			int leng = this.path.length();
			int nameLeng = this.name.length();
			this.parentFolderPath=this.path.substring(0, leng-nameLeng-1);
			System.out.println(this.parentFolderPath);
		}
		return this.parentFolderPath;
	}

	public void setParentFolderPath(String parentFolderPath) {
		this.parentFolderPath = parentFolderPath;
	}

	public String getMakeDate() {
		return makeDate;
	}

	public void setMakeDate(String makeDate) {
		this.makeDate = makeDate;
	}

	public String getAlterDate() {
		return alterDate;
	}

	public void setAlterDate(String alterDate) {
		this.alterDate = alterDate;
	}
	
}
