package model;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OriginProject.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class OriginProject extends OriginFolder {
	private List<String> tagList=null;
	private List<String> sharedMemberList=null;
	private String owner;
	
	public OriginProject(String path) {
		super(path);
		this.tagList = new ArrayList<String>();
		this.sharedMemberList = new ArrayList<String>();
	}
/*	public OriginProject(String owner,String path, String name, String description) {
		super(path,  name, description);
		this.tagList = new ArrayList<String>();
		this.sharedMemberList = new ArrayList<String>();
		this.owner = owner;
	}
	public OriginProject(String owner,String path, String name, String description,String makeDate) {
		super(path,  name, description, makeDate);
		this.tagList = new ArrayList<String>();
		this.sharedMemberList = new ArrayList<String>();
		this.owner = owner;
	}
	public OriginProject(String code,String owner,String path, String name, String description,String makeDate) {
		super(code, path,  name, description, makeDate);
		this.tagList = new ArrayList<String>();
		this.sharedMemberList = new ArrayList<String>();
		this.owner = owner;
	}
	public OriginProject(String code,String owner,String path, String name, String description,String makeDate,String parentFolder) {
		super(code, path, name, description, makeDate, parentFolder);
		this.tagList = new ArrayList<String>();
		this.sharedMemberList = new ArrayList<String>();
		this.owner = owner;
	}*/
	
	public OriginProject(String owner,String path, String name, String makeDate,String parentFolder) {
		super(path, name, makeDate, parentFolder);
		this.tagList = new ArrayList<String>();
		this.sharedMemberList = new ArrayList<String>();
		this.owner = owner;
	}
	public OriginProject(String owner,String path, String name, String makeDate,
			String parentFolder, String description,int size) {
		super( path, name, makeDate, parentFolder, description, size);
		this.tagList = new ArrayList<String>();
		this.sharedMemberList = new ArrayList<String>();
		this.owner = owner;
	}
	
	public OriginProject(String owner,String code,String path, String name, String makeDate,String parentFolder) {
		super(code, path, name, makeDate, parentFolder);
		this.tagList = new ArrayList<String>();
		this.sharedMemberList = new ArrayList<String>();
		this.owner = owner;
	}
	public OriginProject(String owner,String code,String path, String name, String makeDate,String parentFolder, String description,int size) {
		super(code, path, name, makeDate, parentFolder, description, size);
		this.tagList = new ArrayList<String>();
		this.sharedMemberList = new ArrayList<String>();
		this.owner = owner;
	}
	
	public List<String> getTagList() {
		return tagList;
	}
	public void setTagList(List<String> tagList) {
		this.tagList = tagList;
	}
	public List<String> getSharedMemberList() {
		return sharedMemberList;
	}
	public void setSharedMemberList(List<String> sharedMemberList) {
		this.sharedMemberList = sharedMemberList;
	}
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}	
}
