package dto;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EnrollOriginProjectDTO.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class EnrollOriginProjectDTO {
	private String owner;
	private String name;
	private String description;
	private String makeDate;
	private List<String> tagList;
	private String folderCode;
	public EnrollOriginProjectDTO() {
	}
	public EnrollOriginProjectDTO(String owner, String name,
			String description, String makeDate, List<String> tagList,String folderCode) {
		this.owner = owner;
		this.name = name;
		this.description = description;
		this.makeDate = makeDate;
		this.tagList = tagList;
		this.folderCode = folderCode;
	}
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getMakeDate() {
		return makeDate;
	}
	public void setMakeDate(String makeDate) {
		this.makeDate = makeDate;
	}
	public List<String> getTagList() {
		return tagList;
	}
	public void setTagList(List<String> tagList) {
		this.tagList = tagList;
	}
	public String getFolderCode() {
		return folderCode;
	}
	public void setFolderCode(String folderCode) {
		this.folderCode = folderCode;
	}
	
	
}
