package dto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EnrollCommentInfoDTO.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class EnrollCommentInfoDTO {
	private String objectKind;
	private String objectCode;
	private String content;
	private String makeDate;
	private String member;
	public EnrollCommentInfoDTO() {
	}
	public EnrollCommentInfoDTO(String objectKind, String objectCode,
			String content, String makeDate, String member) {
		this.objectKind = objectKind;
		this.objectCode = objectCode;
		this.content = content;
		this.makeDate = makeDate;
		this.member = member;
	}
	public String getObjectKind() {
		return objectKind;
	}
	public void setObjectKind(String objectKind) {
		this.objectKind = objectKind;
	}
	public String getObjectCode() {
		return objectCode;
	}
	public void setObjectCode(String objectCode) {
		this.objectCode = objectCode;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getMakeDate() {
		return makeDate;
	}
	public void setMakeDate(String makeDate) {
		this.makeDate = makeDate;
	}
	public String getMember() {
		return member;
	}
	public void setMember(String member) {
		this.member = member;
	}
	
	
}
