package dto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LogInfoDTO.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class LogDTO {
	private String code;
	private String setCode;
	private String kind;
	private String logDate;
	public LogDTO() {
	}
	public LogDTO(String setCode, String kind, String logDate) {
		this.setCode = setCode;
		this.kind = kind;
		this.logDate = logDate;
	}
	public LogDTO(String code, String setCode, String kind, String logDate) {
		this.code = code;
		this.setCode = setCode;
		this.kind = kind;
		this.logDate = logDate;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getSetCode() {
		return setCode;
	}
	public void setSetCode(String setCode) {
		this.setCode = setCode;
	}
	public String getKind() {
		return kind;
	}
	public void setKind(String kind) {
		this.kind = kind;
	}
	public String getLogDate() {
		return logDate;
	}
	public void setLogDate(String logDate) {
		this.logDate = logDate;
	}
	
	
}
