package dto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TeamCooperatorDTO.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class TeamCooperatorDTO {
	private String code;
	private String nickName;
	private String email;
	public TeamCooperatorDTO() {
	}
	public TeamCooperatorDTO(String code, String nickName, String email) {
		this.code = code;
		this.nickName = nickName;
		this.email = email;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getNickName() {
		return nickName;
	}
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
	
}
