package dto;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TeamDTO.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class TeamDTO {
	private String code;
	private String name;
	private String description;
	private String manager;
	public TeamDTO() {
	}
	public TeamDTO(String code, String name, String description,
			String manager) {
		this.code = code;
		this.name = name;
		this.description = description;
		this.manager = manager;
		
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getManager() {
		return manager;
	}
	public void setManager(String manager) {
		this.manager = manager;
	}
		
}
