package manager;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FolderModifiable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface FolderModifiable {
	public boolean modifyFolderPath(String nickName, String code, String newPath);
	public boolean modifyFolderName(String nickName, String code, String newName);
	public boolean modifyFolderDes(String nickName, String code, String newDescription);
}
