package manager;

import socialProExceptions.DAOException;
import socialProExceptions.MemberException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberLoginable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface MemberLoginable {
	public boolean loginMember(String nickName,String pw)throws DAOException, MemberException;
}
