package manager;

import socialProExceptions.DAOException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberModifiable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface MemberModifiable {
	public boolean modifyMember(String code,String nickName, String email, String pw, String school, int entranceYear)throws DAOException;
}
