package manager;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import model.Alarm;
import model.CommitInfo;
import model.CommitMessage;
import model.CooperatorMessage;
import model.CopiedProject;
import model.GroupAlarm;
import model.Message;
import model.OriginProject;
import socialProExceptions.CommitExcetion;
import socialProExceptions.DAOException;
import socialProExceptions.FileException;
import socialProExceptions.FolderException;
import socialProExceptions.MemberException;
import socialProExceptions.ProjectException;
import socialProExceptions.RemoteFileException;
import socialProExceptions.TeamException;

import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.SftpException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ Message Name : MessageManager.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class MessageManager implements MessageModifyable, MessageSearchable, MessageCreatable, MessageDetelable{
	
	private static MessageManager INSTANCE;
	private Map<String,Message> msgMap;
	
	static{
		INSTANCE = new MessageManager();
	}
	
	private MessageManager(){
		this.msgMap = new HashMap<String, Message>();
	}

	public static MessageManager getINSTANCE() {
		return INSTANCE;
	}

	public void putMessage(Message msg){
		
		String msgCode = msg.getMessageCode();
		if(this.msgMap.containsKey(msgCode)) this.msgMap.remove(msgCode);
		if(msg instanceof CooperatorMessage){System.out.println("   @@@@ cooper");this.msgMap.put(msgCode, (CooperatorMessage)msg);System.out.println(this.msgMap.get(msgCode).getContent());}
		else if (msg instanceof CommitMessage) {System.out.println("   @@@@ commit  ");this.msgMap.put(msgCode, (CommitMessage)msg);System.out.println(this.msgMap.get(msgCode).getContent());}
	}
	
	public Map<Alarm,CommitMessage> putTeamCommitMessageSendToOwner(String title,String content, String senderCode, String ownerCode, List<String> commitList, String teamCode, String copiedProjectCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, TeamException, SftpException, JSchException, CommitExcetion, MemberException, FileException, RemoteFileException{
		//
		String oriProCode = TeamFileNodeManager.getINSTANCE().searchTeamOriProject(teamCode, senderCode, copiedProjectCode).getCode();
		Map<String,List<String>> commitMap = CommitInfoManager.getINSTANCE().searchCommitCodeListForCodeMap(commitList);
		CommitMessage commitMsg = new CommitMessage(title, content, senderCode, ownerCode, new GregorianCalendar(), commitMap);
		Map<Alarm,CommitMessage> resMap = MessageDBManager.getINSTANCE().insertTeamCommitMessageSendToOwner(commitMsg);
		if(!resMap.isEmpty()){
			for(Alarm alarm : resMap.keySet()){
				commitMsg = resMap.get(alarm);
				this.msgMap.put(commitMsg.getMessageCode(), commitMsg);
				MemberAlarmManager.getINSTANCE().insertNewAlarm(commitMsg.getReceiverCode(), "commitMessage", alarm.getAlarmCode());
				AlarmManager.getINSTANCE().putAlarm(alarm);
			}
		}
		return resMap;
	}
	
	public void putShareProjectCommitMessageSendToOwner(String title,String content, String senderCode, String ownerCode, List<String> commitList, String teamCode, String copiedProjectCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, TeamException, SftpException, JSchException, CommitExcetion, MemberException, FileException, RemoteFileException{

		String oriProCode = TeamFileNodeManager.getINSTANCE().searchTeamOriProject(teamCode, senderCode, copiedProjectCode).getCode();
		Map<String,List<String>> commitMap = CommitInfoManager.getINSTANCE().searchCommitCodeListForCodeMap(commitList);
		CommitMessage commitMsg = new CommitMessage(title, content, senderCode, ownerCode, new GregorianCalendar(), commitMap);
		Map<Alarm,CommitMessage> resMap = MessageDBManager.getINSTANCE().insertSharedProjectCommitMessageSendToOwner(commitMsg);
		if(!resMap.isEmpty()){
			for(Alarm alarm : resMap.keySet()){
				commitMsg = resMap.get(alarm);
				this.msgMap.put(commitMsg.getMessageCode(), commitMsg);
				MemberAlarmManager.getINSTANCE().insertNewAlarm(ownerCode, "commitMessage", alarm.getAlarmCode());
				AlarmManager.getINSTANCE().putAlarm(alarm);
			}
		}
	}
	
	public Map<Alarm,CommitMessage> putTeamCommitMessageSendToOwner(CommitMessage commitMsg,String oriProCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, TeamException{
		//
		Map<Alarm,CommitMessage> resMap = MessageDBManager.getINSTANCE().insertTeamCommitMessageSendToOwner(commitMsg);
		if(!resMap.isEmpty()){
			for(Alarm alarm : resMap.keySet()){
				commitMsg = resMap.get(alarm);
				this.msgMap.put(commitMsg.getMessageCode(), commitMsg);
				MemberAlarmManager.getINSTANCE().insertNewAlarm(commitMsg.getReceiverCode(), "commitMessage", alarm.getAlarmCode());
				AlarmManager.getINSTANCE().putAlarm(alarm);
			}
		}
		return resMap;
	}
	
	public Map<Alarm,CommitMessage> putShareProjectCommitMessageSendToOwner(CommitMessage commitMsg,String oriProCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, TeamException{

		System.out.println("\n       MessageManager  putShareProjectCommitMessageSendToOwner  line  110 ");
		Map<Alarm,CommitMessage> resMap = MessageDBManager.getINSTANCE().insertSharedProjectCommitMessageSendToOwner(commitMsg);
		if(!resMap.isEmpty()){
			for(Alarm alarm : resMap.keySet()){
				//insert alarm in manager
				System.out.println("alalrmCode : "+alarm.getAlarmCode());
				commitMsg = resMap.get(alarm);
				this.msgMap.put(commitMsg.getMessageCode(), commitMsg);
				
				AlarmManager.getINSTANCE().putAlarm(alarm);
				MemberAlarmManager.getINSTANCE().insertNewAlarm(commitMsg.getReceiverCode(), "commitMessage", alarm.getAlarmCode());
			}
		}
		return resMap;
	}
	
	public Map<GroupAlarm,CommitMessage> putTeamCommitMessageSendFromOwner(CommitMessage commitMsg,String oriProCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, TeamException{
		//
		Map<GroupAlarm, CommitMessage> resCommitMsgAlarm = MessageDBManager.getINSTANCE().insertTeamCommitMessageFromOwner(commitMsg);
		if(!resCommitMsgAlarm.isEmpty()){
			Map<String,Map<GroupAlarm,CommitMessage>> tmpMap = new HashMap<String, Map<GroupAlarm,CommitMessage>>();
			tmpMap.put(oriProCode, resCommitMsgAlarm);
			this.putModelGroup(tmpMap);
		}
		return resCommitMsgAlarm;
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////
	
	///////////////////////////////   load 
	
	public Map<String,Map<Alarm,CommitMessage>> loadReadSharedProjectCommitMsgForOwner(String ownerCode, List<String> oriProCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException, FileException, MemberException{
		
		System.out.println("\n        MessageManager      loadReadSharedProjectCommitMsgForOwner        line    153");
		//owner of sharedProject (owner rec)
		Map<String,Map<Alarm,CommitMessage>> resMap = new HashMap<String, Map<Alarm,CommitMessage>>();
		if(!oriProCodeList.isEmpty()){
			for(String oriProCode : oriProCodeList){
				
				Map<String,Map<String,List<String>>> cooperMap = new HashMap<String, Map<String,List<String>>>();
				
				Map<String,CopiedProject> cpProMap = FileNodeManager.getINSTANCE().searchCoopersCpProjectListByOriProject(ownerCode, oriProCode);
				if(!cpProMap.isEmpty()){
				for(String cooperCode : cpProMap.keySet()){
					CopiedProject cpProject = cpProMap.get(cooperCode);
					if(cpProject!=null){
						Map<String,List<String>> valMap = FileNodeManager.getINSTANCE().searchMemProjectChilds(cooperCode, cpProject.getCode());
						if(!valMap.isEmpty())cooperMap.put(cooperCode, valMap);
					}
				}
				Map<String, Map<Alarm, CommitMessage>> resMsgMap = MessageDBManager.getINSTANCE().loadReadSharedProjectListCommitMsgForOwner(oriProCode, ownerCode, cooperMap);
				if(!resMsgMap.isEmpty()){
					Map<Alarm,CommitMessage> tmpMap = new HashMap<Alarm, CommitMessage>();
					for(Map<Alarm,CommitMessage> msg : resMsgMap.values()){
						if(!msg.isEmpty())tmpMap.putAll(msg);
					}
					if(!tmpMap.isEmpty())resMap.put(oriProCode, tmpMap);
				}
				}
			}
		}
		return resMap;
	}
	
	public Map<String,Map<Alarm,CommitMessage>> loadUnReadSharedProjectCommitMsgForOwner(String ownerCode, List<String> oriProCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException, FileException, MemberException{
		System.out.println("\n        MessageManager      loadUnReadSharedProjectCommitMsgForOwner        line    167");
		//owner of sharedProject (owner rec)		
		Map<String,Map<Alarm,CommitMessage>> resMap = new HashMap<String, Map<Alarm,CommitMessage>>();
		if(!oriProCodeList.isEmpty()){
			for(String oriProCode : oriProCodeList){
				
				Map<String,Map<String,List<String>>> cooperMap = new HashMap<String, Map<String,List<String>>>();
				
				Map<String,CopiedProject> cpProMap = FileNodeManager.getINSTANCE().searchCoopersCpProjectListByOriProject(ownerCode, oriProCode);
				if(!cpProMap.isEmpty()){
				for(String cooperCode : cpProMap.keySet()){
					CopiedProject cpProject = cpProMap.get(cooperCode);
					if(cpProject!=null){
						Map<String,List<String>> valMap = FileNodeManager.getINSTANCE().searchMemProjectChilds(cooperCode, cpProject.getCode());
						if(!valMap.isEmpty())cooperMap.put(cooperCode, valMap);
					}
				}
				Map<String, Map<Alarm, CommitMessage>> resMsgMap = MessageDBManager.getINSTANCE().loadUnReadSharedProjectListCommitMsgForOwner(oriProCode, ownerCode, cooperMap);
				if(!resMsgMap.isEmpty()){
					Map<Alarm,CommitMessage> tmpMap = new HashMap<Alarm, CommitMessage>();
					for(Map<Alarm,CommitMessage> msg : resMsgMap.values()){
						if(!msg.isEmpty())tmpMap.putAll(msg);
					}
					if(!tmpMap.isEmpty())resMap.put(oriProCode, tmpMap);
				}
				}
			}
		}
		return resMap;
	}

	public Map<Alarm,CommitMessage> loadReadSharedProjectCommitMsgForOwner(String ownerCode, String originProjectCode) throws DAOException, ParseException, FolderException, ProjectException, IOException{
		
		//owner of sharedProject (owner rec)
		Map<Alarm,CommitMessage> resMap = new HashMap<Alarm,CommitMessage>();
		Map<String,List<String>> tmpProMap = FileNodeManager.getINSTANCE().searchMemProjectChilds(ownerCode, originProjectCode);
		if(!tmpProMap.isEmpty()){
			resMap = MessageDBManager.getINSTANCE().loadReadSharedProjectCommitMsgForOwner(ownerCode, tmpProMap);
			if(!resMap.isEmpty()){
				Map<String,Map<Alarm,CommitMessage>> reMap = new HashMap<String, Map<Alarm,CommitMessage>>();
				reMap.put(originProjectCode, resMap);
				this.putModel(reMap);
			}
		}
		
		return resMap;
	}

	public Map<Alarm,CommitMessage> loadUnReadSharedProjectCommitMsgForOwner(String ownerCode, String originProjectCode) throws DAOException, ParseException, FolderException, ProjectException, IOException{
		
		//owner of sharedProject (owner rec)
		Map<Alarm,CommitMessage> resMap = new HashMap<Alarm,CommitMessage>();
		Map<String,List<String>> tmpProMap = FileNodeManager.getINSTANCE().searchMemProjectChilds(ownerCode, originProjectCode);
		if(!tmpProMap.isEmpty()){
			resMap = MessageDBManager.getINSTANCE().loadUnReadSharedProjectCommitMsgForOwner(ownerCode, tmpProMap);
			if(!resMap.isEmpty()){
				Map<String,Map<Alarm,CommitMessage>> reMap = new HashMap<String, Map<Alarm,CommitMessage>>();
				reMap.put(originProjectCode, resMap);
				this.putModel(reMap);
			}
		}
		
		return resMap;
	}

	public Map<String,Map<Alarm,CommitMessage>> loadReadSharedProjectListCommitMsgForCooperator(String cooperatorCode, List<String> cpProCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException, FileException{
		
		//cooperator of sharedProject (cooper send)
		Map<String,Map<Alarm,CommitMessage>> resMap = new HashMap<String, Map<Alarm,CommitMessage>>();
		if(!cpProCodeList.isEmpty()){
			Map<String,Map<String,Map<String,List<String>>>> oriProMap = new HashMap<String,Map<String,Map<String,List<String>>>>();
			for(String cpProCode : cpProCodeList){
				CopiedProject cpProject = FileNodeManager.getINSTANCE().searchCopiedProject(cooperatorCode, cpProCode);
				
				if(cpProject!=null){
					String oriOwner = cpProject.getOriginOwnerCode();
					String oriProCode = cpProject.getOriginCode();
					Map<String,List<String>> tmpProMap = FileNodeManager.getINSTANCE().searchMemProjectChilds(cooperatorCode, cpProCode);
					if(!tmpProMap.isEmpty()){
						if(oriProMap.containsKey(oriOwner)){
							oriProMap.get(oriOwner).put(oriProCode, tmpProMap);
						}else{
							Map<String,Map<String,List<String>>> tmpMap = new HashMap<String, Map<String,List<String>>>();
							tmpMap.put(oriProCode, tmpProMap);
							oriProMap.put(oriOwner, tmpMap);
						}
					}					
				}
			}
			
			if(!oriProMap.isEmpty()){
				resMap = MessageDBManager.getINSTANCE().loadReadSharedProjectListCommitMsgForCooperator(cooperatorCode, oriProMap);
				if(!resMap.isEmpty())this.putModel(resMap);
			}
		}
		return resMap;
	}
	
	public Map<String,Map<Alarm,CommitMessage>> loadUnReadSharedProjectListCommitMsgForCooperator(String cooperatorCode, List<String> cpProCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException{
		
		//cooperator of sharedProject (cooper send)
		Map<String,Map<Alarm,CommitMessage>> resMap = new HashMap<String, Map<Alarm,CommitMessage>>();
		if(!cpProCodeList.isEmpty()){
			Map<String,Map<String,Map<String,List<String>>>> oriProMap = new HashMap<String,Map<String,Map<String,List<String>>>>();
			for(String cpProCode : cpProCodeList){
				CopiedProject cpProject = FileNodeManager.getINSTANCE().searchCopiedProject(cooperatorCode, cpProCode);
				if(cpProject!=null){
					String oriOwner = cpProject.getOriginOwnerCode();
					String oriProCode = cpProject.getOriginCode();
					Map<String,List<String>> tmpProMap = FileNodeManager.getINSTANCE().searchMemProjectChilds(cooperatorCode, cpProCode);
					if(!tmpProMap.isEmpty()){
						if(oriProMap.containsKey(oriOwner)){
							oriProMap.get(oriOwner).put(oriProCode, tmpProMap);
						}else{
							Map<String,Map<String,List<String>>> tmpMap = new HashMap<String, Map<String,List<String>>>();
							tmpMap.put(oriProCode, tmpProMap);
							oriProMap.put(oriOwner, tmpMap);
						}
					}					
				}
			}
			
			if(!oriProMap.isEmpty()){
				resMap = MessageDBManager.getINSTANCE().loadUnReadSharedProjectListCommitMsgForCooperator(cooperatorCode, oriProMap);
				if(!resMap.isEmpty())this.putModel(resMap);
			}
		}
		return resMap;
	}

	public Map<Alarm,CommitMessage> loadReadSharedProjectCommitMsgForCooperator(String cooperatorCode, String cpProCode) throws DAOException, ParseException, FolderException, ProjectException, IOException{
		
		//cooperator of sharedProject (cooper send)
		Map<Alarm,CommitMessage> resMap = new HashMap<Alarm,CommitMessage>();
		CopiedProject cpProject = FileNodeManager.getINSTANCE().searchCopiedProject(cooperatorCode, cpProCode);
		if(cpProject!=null){
			String oriOwner = cpProject.getOriginOwnerCode();
			String oriProCode = cpProject.getOriginCode();
			Map<String,List<String>> tmpProMap = FileNodeManager.getINSTANCE().searchMemProjectChilds(oriOwner, oriProCode);
			if(!tmpProMap.isEmpty()){
				resMap = MessageDBManager.getINSTANCE().loadReadSharedProjectCommitMsgForCooperator(cooperatorCode, oriOwner, tmpProMap);
				if(!resMap.isEmpty()){
					Map<String,Map<Alarm,CommitMessage>> reMap = new HashMap<String, Map<Alarm,CommitMessage>>();
					reMap.put(oriProCode, resMap);
					this.putModel(reMap);	
				}
			}					
		}
		
		return resMap;
	}
	
	public Map<Alarm,CommitMessage> loadUnReadSharedProjectCommitMsgForCooperator(String cooperatorCode, String cpProCode) throws DAOException, ParseException, FolderException, ProjectException, IOException{

		//cooperator of sharedProject (cooper send)
		Map<Alarm,CommitMessage> resMap = new HashMap<Alarm,CommitMessage>();
		CopiedProject cpProject = FileNodeManager.getINSTANCE().searchCopiedProject(cooperatorCode, cpProCode);
		if(cpProject!=null){
			String oriOwner = cpProject.getOriginOwnerCode();
			String oriProCode = cpProject.getOriginCode();
			Map<String,List<String>> tmpProMap = FileNodeManager.getINSTANCE().searchMemProjectChilds(oriOwner, oriProCode);
			if(!tmpProMap.isEmpty()){
				resMap = MessageDBManager.getINSTANCE().loadReadSharedProjectCommitMsgForCooperator(cooperatorCode, oriOwner, tmpProMap);
				if(!resMap.isEmpty()){
					Map<String,Map<Alarm,CommitMessage>> reMap = new HashMap<String, Map<Alarm,CommitMessage>>();
					reMap.put(oriProCode, resMap);
					this.putModel(reMap);	
				}
			}					
		}
		
		return resMap;
	}
	
	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadReadTeamListProjectCommitMsgForOwner(String managerCode, List<String> teamCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//manager of teamProject (manager rec)
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		if(!teamCodeList.isEmpty()){
			Map<String,Map<String,Map<String,List<String>>>> teamProMaps = new HashMap<String, Map<String,Map<String,List<String>>>>();
			for(String teamCode : teamCodeList){
				
				Map<String,Map<String,List<String>>> tmpTeamProMap = TeamFileNodeManager.getINSTANCE().searchTeamSharedProjectChilds(teamCode);
				if(!tmpTeamProMap.isEmpty()){teamProMaps.put(teamCode, tmpTeamProMap);}
			}
			
			resMap = MessageDBManager.getINSTANCE().loadReadTeamListProjectCommitMsgForOwner(managerCode, teamProMaps);
			if(!resMap.isEmpty()){
				for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
					if(!teamProMap.isEmpty())this.putModel(teamProMap);
				}
			}
		}
		return resMap;
	}
	
	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadUnReadTeamListProjectCommitMsgForOwner(String managerCode, List<String> teamCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//manager of teamProject (manager rec)
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		if(!teamCodeList.isEmpty()){
			Map<String,Map<String,Map<String,List<String>>>> teamProMaps = new HashMap<String, Map<String,Map<String,List<String>>>>();
			for(String teamCode : teamCodeList){
				
				Map<String,Map<String,List<String>>> tmpTeamProMap = TeamFileNodeManager.getINSTANCE().searchTeamSharedProjectChilds(teamCode);
				if(!tmpTeamProMap.isEmpty()){teamProMaps.put(teamCode, tmpTeamProMap);}
			}
			
			resMap = MessageDBManager.getINSTANCE().loadUnReadTeamListProjectCommitMsgForOwner(managerCode, teamProMaps);
			if(!resMap.isEmpty()){
				for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
					if(!teamProMap.isEmpty())this.putModel(teamProMap);
				}
			}
		}
		return resMap;
	}
	

	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadReadTeamProjectListCommitMsgForOwner(String managerCode, String teamCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//manager of teamProject (manager rec)
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		Map<String,Map<String,List<String>>> tmpTeamProMap = TeamFileNodeManager.getINSTANCE().searchTeamSharedProjectChilds(teamCode);
		if(!tmpTeamProMap.isEmpty()){
			resMap = MessageDBManager.getINSTANCE().loadReadTeamProjectListCommitMsgForOwner(teamCode, managerCode, tmpTeamProMap);
			if(!resMap.isEmpty()){
				for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
					if(!teamProMap.isEmpty())this.putModel(teamProMap);
				}
			}
		}
		
		return resMap;
	}
	
	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadUnReadTeamProjectListCommitMsgForOwner(String managerCode, String teamCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//manager of teamProject (manager rec)
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		Map<String,Map<String,List<String>>> tmpTeamProMap = TeamFileNodeManager.getINSTANCE().searchTeamSharedProjectChilds(teamCode);
		if(!tmpTeamProMap.isEmpty()){
			resMap = MessageDBManager.getINSTANCE().loadUnReadTeamProjectListCommitMsgForOwner(teamCode, managerCode, tmpTeamProMap);
			if(!resMap.isEmpty()){
				for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
					if(!teamProMap.isEmpty())this.putModel(teamProMap);
				}
			}
		}
		return resMap;
	}
	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadReadTeamProjectCommitMsgForOwner(String managerCode, String teamCode, String oriProCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion, TeamException, MemberException{
		

		//manager of teamProject (manager rec)
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		Map<String,CopiedProject> cooperCpProMap = TeamFileNodeManager.getINSTANCE().searchTeamCopiedProject(teamCode, oriProCode);
		
		if(cooperCpProMap.isEmpty())return resMap;
		
		Map<String,Map<String,List<String>>> cooperChMap = new HashMap<String, Map<String,List<String>>>();
		for(String cooper : cooperCpProMap.keySet()){
			CopiedProject cpPro = cooperCpProMap.get(cooper);
			Map<String,List<String>> cpChildMap = TeamFileNodeManager.getINSTANCE().searchTeamCopiedProjectChilds(teamCode, cooper, cpPro.getCode());
			
			if(!cpChildMap.isEmpty()){
				cooperChMap.put(cooper, cpChildMap);
			}
		}
		resMap = MessageDBManager.getINSTANCE().loadReadTeamProjectCommitMsgForOwner(teamCode, managerCode, oriProCode, cooperChMap);
		if(!resMap.isEmpty()){
			for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
				if(!teamProMap.isEmpty())this.putModel(teamProMap);
			}
		}
		
		return resMap;
	}
	
	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadUnReadTeamProjectCommitMsgForOwner(String managerCode, String teamCode, String oriProCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion, TeamException, MemberException{

		//manager of teamProject (manager rec)
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		Map<String,CopiedProject> cooperCpProMap = TeamFileNodeManager.getINSTANCE().searchTeamCopiedProject(teamCode, oriProCode);
		
		if(cooperCpProMap.isEmpty())return resMap;
		
		Map<String,Map<String,List<String>>> cooperChMap = new HashMap<String, Map<String,List<String>>>();
		for(String cooper : cooperCpProMap.keySet()){
			CopiedProject cpPro = cooperCpProMap.get(cooper);
			Map<String,List<String>> cpChildMap = TeamFileNodeManager.getINSTANCE().searchTeamCopiedProjectChilds(teamCode, cooper, cpPro.getCode());
			
			if(!cpChildMap.isEmpty()){
				cooperChMap.put(cooper, cpChildMap);
			}
		}
		resMap = MessageDBManager.getINSTANCE().loadUnReadTeamProjectCommitMsgForOwner(teamCode, managerCode, oriProCode, cooperChMap);
		if(!resMap.isEmpty()){
			for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
				if(!teamProMap.isEmpty())this.putModel(teamProMap);
			}
		}
		
		return resMap;
	}
	
	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadReadTeamListProjectCommitMsgForCooper(String cooperatorCode, List<String> teamCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//cooperator of team project
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		if(!teamCodeList.isEmpty()){
			Map<String,Map<String,Map<String,List<String>>>> teamProMaps = new HashMap<String, Map<String,Map<String,List<String>>>>();
			for(String teamCode : teamCodeList){
				
				Map<String,Map<String,List<String>>> tmpTeamProMap = TeamFileNodeManager.getINSTANCE().searchTeamSharedProjectChilds(teamCode);
				if(!tmpTeamProMap.isEmpty()){teamProMaps.put(teamCode, tmpTeamProMap);}
			}
			
			resMap = MessageDBManager.getINSTANCE().loadReadTeamListProjectCommitMsgForCooper(cooperatorCode, teamProMaps);
			if(!resMap.isEmpty()){
				for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
					if(!teamProMap.isEmpty())this.putModel(teamProMap);
				}
			}
		}
		return resMap;
	}

	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadUnReadTeamListProjectCommitMsgForCooper(String cooperatorCode, List<String> teamCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//cooperator of team project
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		if(!teamCodeList.isEmpty()){
			Map<String,Map<String,Map<String,List<String>>>> teamProMaps = new HashMap<String, Map<String,Map<String,List<String>>>>();
			for(String teamCode : teamCodeList){
				
				Map<String,Map<String,List<String>>> tmpTeamProMap = TeamFileNodeManager.getINSTANCE().searchTeamSharedProjectChilds(teamCode);
				if(!tmpTeamProMap.isEmpty()){teamProMaps.put(teamCode, tmpTeamProMap);}
			}
			
			resMap = MessageDBManager.getINSTANCE().loadUnReadTeamListProjectCommitMsgForCooper(cooperatorCode, teamProMaps);
			if(!resMap.isEmpty()){
				for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
					if(!teamProMap.isEmpty())this.putModel(teamProMap);
				}
			}
		}
		return resMap;
	}

	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadReadTeamProjectListCommitMsgForCooper(String cooperatorCode, String teamCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//cooperator of team project
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		Map<String,Map<String,List<String>>> tmpTeamProMap = TeamFileNodeManager.getINSTANCE().searchTeamSharedProjectChilds(teamCode);
		if(!tmpTeamProMap.isEmpty()){
			resMap = MessageDBManager.getINSTANCE().loadReadTeamProjectListCommitMsgForCooper(teamCode, cooperatorCode, tmpTeamProMap);
			if(!resMap.isEmpty()){
				for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
					if(!teamProMap.isEmpty())this.putModel(teamProMap);
				}
			}	
		}
		
		return resMap;
	}

	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadUnReadTeamProjectListCommitMsgForCooper(String cooperatorCode, String teamCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{

		//cooperator of team project
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		Map<String,Map<String,List<String>>> tmpTeamProMap = TeamFileNodeManager.getINSTANCE().searchTeamSharedProjectChilds(teamCode);
		if(!tmpTeamProMap.isEmpty()){
			resMap = MessageDBManager.getINSTANCE().loadUnReadTeamProjectListCommitMsgForCooper(teamCode, cooperatorCode, tmpTeamProMap);
			if(!resMap.isEmpty()){
				for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
					if(!teamProMap.isEmpty())this.putModel(teamProMap);
				}
			}	
		}
		
		return resMap;
	}

	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadReadTeamProjectCommitMsgForCooper(String oriProCode,String cooperatorCode, String teamCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion, MemberException, TeamException{
		

		//cooperator of team project
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		CopiedProject cpPro = TeamFileNodeManager.getINSTANCE().searchTeamCopiedProject(teamCode, oriProCode).get(cooperatorCode);
		if(cpPro!=null){
			
			Map<String,List<String>> tmpVal = TeamFileNodeManager.getINSTANCE().searchTeamCopiedProjectChilds(teamCode, cooperatorCode, cpPro.getCode());
			if(!tmpVal.isEmpty()){
				String manager = TeamManager.getINSTANCE().searchTeamCode(teamCode).getManager();
				resMap = MessageDBManager.getINSTANCE().loadReadTeamProjectCommitMsgForCooper(teamCode, manager, cooperatorCode, oriProCode, tmpVal);
				if(!resMap.isEmpty()){
					for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
						if(!teamProMap.isEmpty())this.putModel(teamProMap);
					}
				}
			}
			
		}
		
		return resMap;
	}

	public Map<String, Map<String,Map<Alarm, CommitMessage>>> loadUnReadTeamProjectCommitMsgForCooper(String oriProCode,String cooperatorCode, String teamCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion, TeamException, MemberException{

		//cooperator of team project
		Map<String, Map<String,Map<Alarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<Alarm,CommitMessage>>>();
		CopiedProject cpPro = TeamFileNodeManager.getINSTANCE().searchTeamCopiedProject(teamCode, oriProCode).get(cooperatorCode);
		if(cpPro!=null){
			
			Map<String,List<String>> tmpVal = TeamFileNodeManager.getINSTANCE().searchTeamCopiedProjectChilds(teamCode, cooperatorCode, cpPro.getCode());
			if(!tmpVal.isEmpty()){
				String manager = TeamManager.getINSTANCE().searchTeamCode(teamCode).getManager();
				resMap = MessageDBManager.getINSTANCE().loadUnReadTeamProjectCommitMsgForCooper(teamCode, manager, cooperatorCode, oriProCode, tmpVal);
				if(!resMap.isEmpty()){
					for(Map<String,Map<Alarm, CommitMessage>> teamProMap : resMap.values()){
						if(!teamProMap.isEmpty())this.putModel(teamProMap);
					}
				}
			}
			
		}
		
		return resMap;
	}
	
	public Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> loadReadTeamProjectCommitMessageForTeam(String cooperatorCode, List<String> teamCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//cooperator of team project
		Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<GroupAlarm,CommitMessage>>>();
		if(!teamCodeList.isEmpty()){
			Map<String,List<String>> teamProMaps = new HashMap<String,List<String>>();
			for(String teamCode : teamCodeList){
				
				List<String> tmpTeamProList = TeamFileNodeManager.getINSTANCE().searchTeamProjectList(teamCode);
				if(!tmpTeamProList.isEmpty()){teamProMaps.put(teamCode, tmpTeamProList);}
			}
			resMap = MessageDBManager.getINSTANCE().loadReadTeamProjectCommitMessageForTeam(cooperatorCode, teamProMaps);
			if(!resMap.isEmpty()){
				for(Map<String, Map<GroupAlarm, CommitMessage>> groupMap : resMap.values()){
					if(!groupMap.isEmpty()){this.putModelGroup(groupMap);}
				}
			}
		}
		
		return resMap;
	}
	
	public Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> loadUnReadTeamProjectCommitMessageForTeam(String cooperatorCode, List<String> teamCodeList) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//cooperator of team project
		Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<GroupAlarm,CommitMessage>>>();
		
		if(!teamCodeList.isEmpty()){
			Map<String,List<String>> teamProMaps = new HashMap<String,List<String>>();
			for(String teamCode : teamCodeList){
				
				List<String> tmpTeamProList = TeamFileNodeManager.getINSTANCE().searchTeamProjectList(teamCode);
				if(!tmpTeamProList.isEmpty()){teamProMaps.put(teamCode, tmpTeamProList);}
			}
			resMap = MessageDBManager.getINSTANCE().loadUnReadTeamProjectCommitMessageForTeam(cooperatorCode, teamProMaps);
			if(!resMap.isEmpty()){
				for(Map<String, Map<GroupAlarm, CommitMessage>> groupMap : resMap.values()){
					if(!groupMap.isEmpty()){this.putModelGroup(groupMap);}
				}
			}
		}
		
		return resMap;
	}

	public Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> loadReadTeamProjectListCommitMessageForTeam(Map<String,List<String>> teamSharedProjectMap) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{

		//cooperator of team project
		Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<GroupAlarm,CommitMessage>>>();
		
		if(!teamSharedProjectMap.isEmpty()){
			
			resMap = MessageDBManager.getINSTANCE().loadReadTeamProjectListCommitMessageForTeam(teamSharedProjectMap);
			if(!resMap.isEmpty()){
				for(Map<String, Map<GroupAlarm, CommitMessage>> groupMap : resMap.values()){
					if(!groupMap.isEmpty()){this.putModelGroup(groupMap);}
				}
			}
		}
		
		return resMap;
	}
	
	public Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> loadUnReadTeamProjectListCommitMessageForTeam(Map<String,List<String>> teamSharedProjectMap) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{
		
		//cooperator of team project
		Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<GroupAlarm,CommitMessage>>>();
		
		if(!teamSharedProjectMap.isEmpty()){
			
			resMap = MessageDBManager.getINSTANCE().loadUnReadTeamProjectListCommitMessageForTeam(teamSharedProjectMap);
			if(!resMap.isEmpty()){
				for(Map<String, Map<GroupAlarm, CommitMessage>> groupMap : resMap.values()){
					if(!groupMap.isEmpty()){this.putModelGroup(groupMap);}
				}
			}
		}
		
		return resMap;
	}

	public Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> loadReadTeamProjectCommitMessageForTeam(String teamCode, String teamOriProCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{

		//cooperator of team project
		Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<GroupAlarm,CommitMessage>>>();
		resMap = MessageDBManager.getINSTANCE().loadReadTeamProjectCommitMessageForTeam(teamCode, teamOriProCode);
		if(!resMap.isEmpty()){
			for(Map<String, Map<GroupAlarm, CommitMessage>> groupMap : resMap.values()){
				if(!groupMap.isEmpty()){this.putModelGroup(groupMap);}
			}
		}
		return resMap;
	}
	
	public Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> loadUnReadTeamProjectCommitMessageForTeam(String teamCode, String teamOriProCode) throws DAOException, ParseException, FolderException, ProjectException, IOException, SftpException, JSchException, CommitExcetion{

		//cooperator of team project
		Map<String, Map<String, Map<GroupAlarm, CommitMessage>>> resMap = new HashMap<String, Map<String,Map<GroupAlarm,CommitMessage>>>();
		resMap = MessageDBManager.getINSTANCE().loadUnReadTeamProjectCommitMessageForTeam(teamCode, teamOriProCode);
		if(!resMap.isEmpty()){
			for(Map<String, Map<GroupAlarm, CommitMessage>> groupMap : resMap.values()){
				if(!groupMap.isEmpty()){this.putModelGroup(groupMap);}
			}
		}
		return resMap;
	}
	
	///////////////////////////////////////////////////////////
	
	public Message getMessageByCode(String msgCode){
		if(!this.msgMap.containsKey(msgCode))return null;
		if(this.msgMap.get(msgCode) instanceof CooperatorMessage)return (CooperatorMessage)this.msgMap.get(msgCode);
		else if(this.msgMap.get(msgCode) instanceof CommitMessage)return (CommitMessage)this.msgMap.get(msgCode);
		else return this.msgMap.get(msgCode);
	}

	public CommitMessage getCommitMessage(String msgCode) throws DAOException, ParseException{
		if(!this.msgMap.containsKey(msgCode)) {
			System.out.println("WHY...............");
			Map<Alarm,CommitMessage> resMap = MessageDBManager.getINSTANCE().searchCommitMessage(msgCode);
			if(resMap.isEmpty()) return null;
			Alarm alarm = resMap.keySet().iterator().next();
			CommitMessage msg = resMap.get(alarm);
			AlarmManager.getINSTANCE().putAlarm(alarm);
			this.putMessage(msg);
		}
		if(this.msgMap.get(msgCode) instanceof CommitMessage){System.out.println("¼³¸¶..........");System.out.println(((CommitMessage)this.msgMap.get(msgCode)).getContent());
		return ((CommitMessage)this.msgMap.get(msgCode));}
		else return null;
	}

	public CooperatorMessage getCooperatorMessage(String msgCode){
		if(!this.msgMap.containsKey(msgCode))return null;
		if(this.msgMap.get(msgCode) instanceof CooperatorMessage)return (CooperatorMessage)this.msgMap.get(msgCode);
		else return null;
	}

	public Message getMessage(String msgCode){
		if(!this.msgMap.containsKey(msgCode))return null;
		if(this.msgMap.get(msgCode) instanceof CooperatorMessage)return null;
		else if(this.msgMap.get(msgCode) instanceof CommitMessage)return null;
		else return this.msgMap.get(msgCode);
	}
	
	public List<CommitInfo> searchCommitMsgCommitList(String commitMsgCode, String objCode) throws DAOException, ParseException, FileNotFoundException, FileException, SftpException, IOException, JSchException, RemoteFileException, FolderException, MemberException, ProjectException, TeamException{
		
		List<CommitInfo> resList = new ArrayList<CommitInfo>();
		CommitMessage commitMsg = this.getCommitMessage(commitMsgCode);
		if(commitMsg==null)return resList;
		
		Map<String, List<String>> commitCodeMap  = commitMsg.getCommitMap();
		if(commitCodeMap.isEmpty())return resList;
		List<String> commitCodeList = new ArrayList<>();
		commitCodeList = commitCodeMap.get(objCode);
		for(String commitCode : commitCodeList){
			CommitInfo commitInfo = CommitInfoManager.getINSTANCE().searchCommitCode(commitCode);
			if(commitInfo!=null)resList.add(commitInfo);
		}
		
		int cnt = resList.size();
		for(int i=0;i<cnt;i++){
			for(int k=0;k<cnt-i-1;k++){
				CommitInfo largeCommit = resList.get(k);
				CommitInfo smallCommit = resList.get(k);
				DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
				Date date = df.parse(largeCommit.getDate());
				GregorianCalendar large = (GregorianCalendar)Calendar.getInstance();
				large.setTime(date);
				
				DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
				Date date1 = df1.parse(smallCommit.getDate());
				GregorianCalendar small = (GregorianCalendar)Calendar.getInstance();
				small.setTime(date1);
				
				if(large.getTime().compareTo(small.getTime())>0){
					//change
					resList.remove(k);resList.remove(k+1);
					resList.add(k, smallCommit);resList.add(k+1, largeCommit);
				}
			}
		}
		
		return resList;
	}

	public Map<String,List<CommitInfo>> searchCommitMsgCommitList(String commitMsgCode) throws DAOException, ParseException, FileNotFoundException, FileException, SftpException, IOException, JSchException, RemoteFileException, FolderException, MemberException, ProjectException, TeamException{
		
		System.out.println("\n         MessageManager   searchCommitMsgCommitList     line     801  "+commitMsgCode);
		Map<String,List<CommitInfo>> resMap = new HashMap<String, List<CommitInfo>>();
		CommitMessage commitMsg = this.getCommitMessage(commitMsgCode);
		if(commitMsg==null){
			System.out.println("commitMsg is nulll.....wha??");
			return resMap;
		}
		
		Map<String, List<String>> commitCodeMap  = commitMsg.getCommitMap();
		if(commitCodeMap.isEmpty())return resMap;
		
		for(String obj : commitCodeMap.keySet()){
		List<String> commitCodeList = commitCodeMap.get(obj);
		if(!commitCodeList.isEmpty()){
			List<CommitInfo> val =  new ArrayList<CommitInfo>();
			for(String commitCode : commitCodeList){
				System.out.println("commitCode in to List  : "+commitCode);
				CommitInfo commitInfo = CommitInfoManager.getINSTANCE().searchCommitCode(commitCode);
				if(commitInfo!=null){val.add(commitInfo);}
			}
			resMap.put(obj, val);
		}
		}
		
		
		
		if(resMap.isEmpty())System.out.println("resMap is empty.......bb");
		else System.out.println("resMap is not Empty!!!!!! ok!!");
		return resMap;
	}
	
////////////////////////////////////////////////////////////////////////////////////////	
	
	public void putProCommitMsgSendToOwner(){
		
	}
	
	
	private void putModel(Map<String,Map<Alarm,CommitMessage>> resMap){
		for(Map<Alarm,CommitMessage> tmpVal : resMap.values()){
			if(!tmpVal.isEmpty()){
				for(CommitMessage commitMsg : tmpVal.values()){
					if(this.msgMap.containsKey(commitMsg.getMessageCode()))this.msgMap.remove(commitMsg.getMessageCode());
					this.msgMap.put(commitMsg.getMessageCode(), commitMsg);	
				}
			}
		}
	}
	
	private void putModelGroup(Map<String,Map<GroupAlarm,CommitMessage>> resMap){
		for(Map<GroupAlarm, CommitMessage> tmpVal : resMap.values()){
			if(!tmpVal.isEmpty()){
				for(CommitMessage commitMsg : tmpVal.values()){
					if(this.msgMap.containsKey(commitMsg.getMessageCode()))this.msgMap.remove(commitMsg.getMessageCode());
					this.msgMap.put(commitMsg.getMessageCode(), commitMsg);	
				}
			}
		}
	}
}
