package manager;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.util.List;
import java.util.Map;

import model.FileNode;
import socialProExceptions.CommitExcetion;
import socialProExceptions.DAOException;
import socialProExceptions.FileException;
import socialProExceptions.FolderException;
import socialProExceptions.MemberException;
import socialProExceptions.ProjectException;
import socialProExceptions.RemoteFileException;
import socialProExceptions.TagException;
import socialProExceptions.TeamException;

import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.SftpException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProjectCreatable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface ProjectCreatable {
	public String createProject(String memberCode,String nickName, String name, String description, String path, List<String> tagList)throws DAOException, ParseException, SftpException, JSchException, ProjectException, FolderException, TagException;
	public String createProject(String memberCode,String nickName, String name, String description, String path, List<String> tagList,String commitTitle,String commitContent)throws DAOException, ParseException, SftpException, JSchException, CommitExcetion, FolderException, ProjectException, TagException, FileNotFoundException, IOException, MemberException, FileException, RemoteFileException, TeamException;
	public String createProject(String memberCode,String nickName, String name, String path, List<String> tagList) throws DAOException, ParseException, SftpException, JSchException, ProjectException, FolderException, TagException;
	public List<File> createTeamProject(String teamCode,String teamName,String projectName,String proDes,String path,List<String> tagList,String commitTitle, String commitContent) throws DAOException, SftpException, JSchException, FolderException, ProjectException, TeamException, CommitExcetion, TagException, FileNotFoundException, ParseException, IOException, MemberException, FileException, RemoteFileException;
	public Map<String,FileNode> copyTeamProjects(List<FileNode> projectList,String memberCode,String teamCode) throws FileNotFoundException, DAOException, MemberException, TeamException, SftpException, JSchException, FolderException, ProjectException, ParseException, IOException, FileException, RemoteFileException, CommitExcetion;
	public FileNode copyOriginProject(FileNode project,String memberCode,String ownerCode) throws FileNotFoundException, DAOException, MemberException, TeamException, SftpException, JSchException, IOException, FolderException, ProjectException, ParseException, FileException, RemoteFileException, CommitExcetion;
}
