package manager;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProjectInfoModifiable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface ProjectInfoModifiable {
	public boolean modifyProject(String nickName, String name, String descriptioin, String path, String parentFolder, List<String> tagList);
}
