package model;

import java.io.File;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CopiedFile.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class CopiedFile extends OriginFile {
	private String originFileCode;
	private String originFolderCode;
	private String copyDate;
	public CopiedFile(String path) {
		super(path);
	}
	
	public CopiedFile(File file){
		super(file.getPath());
	}
	
	public CopiedFile(String name, String path, String makeDate,String folderCode,String oriFildeCode, String oriFolderCode) {
		super(name, path, makeDate, folderCode);
		this.originFileCode = oriFildeCode;
		this.originFolderCode = oriFolderCode;
	}
	public CopiedFile(String name, String path, String makeDate,
			String folderCode, String content,int sizes,String oriFildeCode, String oriFolderCode) {
		super(name, path, makeDate, folderCode, content, sizes);
		this.originFileCode = oriFildeCode;
		this.originFolderCode = oriFolderCode;
	}
	
	public CopiedFile(String code,String name, String path, String makeDate,String folderCode,String oriFildeCode, String oriFolderCode) {
		super(code, name, path, makeDate, folderCode);
		this.originFileCode = oriFildeCode;
		this.originFolderCode = oriFolderCode;
	}
	public CopiedFile(String code,String name, String path, String makeDate,
			String folderCode, String content,int sizes,String oriFildeCode, String oriFolderCode) {
		super(code, name, path, makeDate, folderCode, content, sizes);
		this.originFileCode = oriFildeCode;
		this.originFolderCode = oriFolderCode;
	}
	/*
	public CopiedFile(String name, String path, String makeDate,String folderCode) {
		super(name, path, makeDate, folderCode);
	}
	public CopiedFile(String name, String path, String makeDate,
			String folderCode, String content,int sizes) {
		super(name, path, makeDate, folderCode, content, sizes);
	}
	
	public CopiedFile(String code,String name, String path, String makeDate,String folderCode) {
		super(code, name, path, makeDate, folderCode);
	}
	public CopiedFile(String code,String name, String path, String makeDate,
			String folderCode, String content,int sizes) {
		super(code, name, path, makeDate, folderCode, content, sizes);
	}
*/
	public String getOriginFileCode() {
		return originFileCode;
	}


	public void setOriginFileCode(String originFileCode) {
		this.originFileCode = originFileCode;
	}


	public String getOriginFolderCode() {
		return originFolderCode;
	}


	public void setOriginFolderCode(String originFolderCode) {
		this.originFolderCode = originFolderCode;
	}


	public String getCopyDate() {
		return copyDate;
	}


	public void setCopyDate(String copyDate) {
		this.copyDate = copyDate;
	}
	
	
}
