package model;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CopiedFolder.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class CopiedFolder extends OriginFolder {
	private String originCode;
	private String originParentCode;

	public CopiedFolder(String path) {
		super(path);
	}
/*
	public CopiedFolder(OriginFolder oriF,String originCode,String originParentCode) {
		super(oriF.getCode(), oriF.getPath(), oriF.getDescription(), oriF.getMakeDate(), oriF.getParentFolder());
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}
	public CopiedFolder(String path, String name, String description,String originCode,String originParentCode) {
		super(path, name, description);
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}
	public CopiedFolder(String path, String name, String description,String makeDate,String originCode,String originParentCode) {
		super(path, name, description, makeDate);
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}
	public CopiedFolder(String path, String name, String description,String makeDate, String parentFolder,String originCode,String originParentCode) {
		super(path, name, description, makeDate,parentFolder);
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}
	public CopiedFolder(String code,String path, String name, String description,String makeDate,String parentFolder,String originCode,String originParentCode) {
		super(code, path, name, description, makeDate, parentFolder);
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}*/
	public CopiedFolder(OriginFolder oriF,String originCode,String originParentCode) {
		super(oriF.getCode(),  oriF.getPath(), oriF.getName(), oriF.getMakeDate(), oriF.getParentFolder(), oriF.getDescription(), 0);
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}
	public CopiedFolder(String path, String name, String makeDate,String parentFolder,String originCode,String originParentCode) {
		super(path, name, makeDate, parentFolder);
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}
	public CopiedFolder(String path, String name, String makeDate,
			String parentFolder, String description,int size,String originCode,String originParentCode) {
		super(path, name, makeDate, parentFolder, description, size);
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}
	
	public CopiedFolder(String code,String path, String name, String makeDate,String parentFolder,String originCode,String originParentCode) {
		super(code, path, name, makeDate, parentFolder);
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}
	public CopiedFolder(String code,String path, String name, String makeDate,String parentFolder, String description,int size,String originCode,String originParentCode) {
		super(code, path, name, makeDate, parentFolder, description, size);
		this.originCode = originCode;
		this.originParentCode = originParentCode;
	}
	
	public String getOriginCode() {
		return originCode;
	}
	public void setOriginCode(String originCode) {
		this.originCode = originCode;
	}
	public String getOriginParentCode() {
		return originParentCode;
	}
	public void setOriginParentCode(String originParentCode) {
		this.originParentCode = originParentCode;
	}
}
