package model;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CopiedProject.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class CopiedProject extends OriginProject {
	private String originCode;
	private String originOwnerCode;
	private String updateDate;
	

	public CopiedProject(String path) {
		super(path);
	}

	public CopiedProject(String path,  String originCode, String originOwnerCode,String updateDate) {
		super(path);
		this.originCode = originCode;
		this.originOwnerCode = originOwnerCode;	
		this.updateDate = updateDate;
	}/*	public CopiedProject(String path, String name,  String originCode, String originOwnerCode,String updateDate) {
		super(path);
		this.originCode = originCode;this.originOwnerCode = originOwnerCode;
	}

	public CopiedProject(String owner,String path, String name,  String description,String originCode, String originOwnerCode,String updateDate) {
		super(owner, path, name, description);
		this.originCode = originCode;
		this.originOwnerCode = originOwnerCode;	
	}
	public CopiedProject(String owner,String path, String name,  String description,String makeDate,String originCode, String originOwnerCode,String updateDate) {
		super(owner, path,  name, description, makeDate);
		this.originCode = originCode;
		this.originOwnerCode = originOwnerCode;	
	}
	public CopiedProject(String code,String owner,String path, String name,  String description,String makeDate,String originCode, String originOwnerCode,String updateDate) {
		super(code, owner, path,  name, description, makeDate);
		this.originCode = originCode;
		this.originOwnerCode = originOwnerCode;	
	}
	public CopiedProject(String code,String owner,String path, String name,  String description,String makeDate,String parentFolder,String originCode, String originOwnerCode,String updateDate) {
		super(code, owner, path,  name, description, makeDate, parentFolder);
		this.originCode = originCode;
		this.originOwnerCode = originOwnerCode;	
	}*/
	
	public CopiedProject(String owner,String path, String name, String makeDate,String parentFolder,String originCode, String originOwnerCode,String updateDate) {
		super(owner, path, name, makeDate, parentFolder);
		this.originCode = originCode;
		this.originOwnerCode = originOwnerCode;
		this.updateDate = updateDate;
	}
	public CopiedProject(String owner,String path, String name, String makeDate,
			String parentFolder, String description,int size,String originCode, String originOwnerCode,String updateDate) {
		super(owner, path, name, makeDate, parentFolder, description, size);
		this.originCode = originCode;
		this.originOwnerCode = originOwnerCode;	
		this.updateDate = updateDate;
	}
	
	public CopiedProject(String owner,String code,String path, String name, String makeDate,String parentFolder,String originCode, String originOwnerCode,String updateDate) {
		super(owner, code, path, name, makeDate, parentFolder);
		this.originCode = originCode;
		this.originOwnerCode = originOwnerCode;	
		this.updateDate = updateDate;
	}
	public CopiedProject(String owner,String code,String path, String name, String makeDate,String parentFolder, String description,int size,String originCode, String originOwnerCode,String updateDate) {
		super(owner, code, path, name, makeDate, parentFolder, description, size);
		this.originCode = originCode;
		this.originOwnerCode = originOwnerCode;	
		this.updateDate = updateDate;
	}
	
	
	public String getOriginCode() {
		return originCode;
	}
	public void setOriginCode(String originCode) {
		this.originCode = originCode;
	}
	public String getOriginOwnerCode() {
		return originOwnerCode;
	}
	public void setOriginOwnerCode(String originOwnerCode) {
		this.originOwnerCode = originOwnerCode;
	}

	public String getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}
	
}
