package model;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TeamList.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class TeamList {
	private List<Team> list;
	
	public TeamList(String name, String description, String manager,
			List<String> cooperatorList, List<String> tagList) {
		this.list = new ArrayList<Team>();
		this.list.add(new Team(name, description, manager, cooperatorList,tagList));
	}
	public TeamList(String name, String description, String manager,
			List<String> tagList) {
		this.list = new ArrayList<Team>();
		this.list.add(new Team(name, description, manager, tagList));
	}
	public TeamList(String code, String name, String description, String manager,
			List<String> tagList) {
		this.list = new ArrayList<Team>();
		this.list.add(new Team(code, name, description, manager, tagList));
	}
	public TeamList(List<String> tagList,String name, String description, String manager,
			List<String> cooperatorList) {
		this.list = new ArrayList<Team>();
		this.list.add(new Team(tagList, name, description, manager, cooperatorList));
	}
	public TeamList() {
		this.list = new ArrayList<Team>();
	}
	
	public boolean addTeam(Team team) {
		return this.list.add(team);
	}
	public int addTeam(List<Team> teamList) {
		int cnt = teamList.size();
		for(int i=0;i<cnt;i++){
			this.list.add(teamList.get(i));
		}
		return cnt;
	}
	
	/*public boolean addTeam(String name, String manager) {
	
	}
	
	public boolean addTeam(String name, String manager, List<String> cooperatorList) {
	
	}
	
	public boolean addTeam(String name, String manager, List<String> cooperatorList, List<String> tagList) {
	
	}
	
	public boolean addTeam(String name, String manager, List<String> cooperatorList, String description) {
	
	}
	
	public boolean addTeam(String name, String manager, List<String> cooperatorList, List<String> tagList, String description) {
	
	}
	*/
	public void deleteTeamName(String name) {
	
	}
	
	public void deleteTeamManager(String manager) {
	
	}
	
	public void modifyTeamCooperator(String cooperator) {
	
	}
	
	public void modifyTeamName(String name, String newName) {
	
	}
	
	public void modifyTeamDescription(String name, String newDescription) {
	
	}
	
	public void modifyTeamAddTag(String name, String addTag) {
	
	}
	
	public void modifyTeamDelTag(String name, String delTag) {
	
	}
	
	public void modifyTeamTag(String name, List<String> newTagList) {
	
	}
	
	public void modifyTeamAddTag(String name, List<String> addTagList) {
	
	}
	
	public Team searchTeamName(String name) {
	
		for(Team t:this.list){
			if(t.getName().equals(name))return t;
		}return null;
	}
	
	public TeamList searchTeamDescription(String description) {
	
		TeamList list = new TeamList();
		for(Team t:this.list){
			if(t.getDescription().equals(description))list.addTeam(t);
		}return list;
	}
	
	public TeamList searchTeamMember(String member) {
	
		TeamList list = new TeamList();
		for(Team t:this.list){
			if(t.getManager().equals(member))list.addTeam(t);
			else {
				for(String str:t.getCooperatorList()){
					if(str.equals(member))list.addTeam(t);
				}}
		}return list;
	}
	
	public TeamList searchTeamManager(String manager) {
	
		TeamList list = new TeamList();
		for(Team t:this.list){
			if(t.getManager().equals(manager))list.addTeam(t);
		}return list;
	}
	
	public TeamList searchTeamCooperator(String cooperator) {
	
		TeamList list = new TeamList();
		for(Team t:this.list){
				for(String str:t.getCooperatorList()){
					if(str.equals(cooperator))list.addTeam(t);
				}
		}return list;
	}
	
	public TeamList searchTeamTag(List<String> tagList) {
	
		TeamList list = new TeamList();
		for(Team t:this.list){
			for(String str:t.getTagList()){
				for(String t1:tagList){
					if(str.equals(t1))list.addTeam(t);
				}
			}
		}return list;
	}
	
	public TeamList searchTeamTag(List<String> tagList, String name, String description) {
	
		TeamList list = new TeamList();
		for(Team t:this.list){
			if(t.getName().equals(name)){
				if(t.getDescription().equals(description)){
					for(String str:t.getTagList()){
						for(String t1:tagList){
							if(str.equals(t1))list.addTeam(t);
						}
					}
				}
			}
		}return list;
	}
	public List<Team> getList() {
		return list;
	}
	public void setList(List<Team> list) {
		this.list = list;
	}
	
}
