package dto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EnrollAlarmInfoDTO.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class EnrollAlarmInfoDTO {
	private String title;
	private String content;
	private int check;
	private String checkDate;
	private String receiver;
	private String kind;
	private String objectCode;
	public EnrollAlarmInfoDTO(String title, String content, int check,
			String checkDate, String receiver, String kind, String objectCode) {
		this.title = title;
		this.content = content;
		this.check = check;
		this.checkDate = checkDate;
		this.receiver = receiver;
		this.kind = kind;
		this.objectCode = objectCode;
	}
	public EnrollAlarmInfoDTO() {
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public int getCheck() {
		return check;
	}
	public void setCheck(int check) {
		this.check = check;
	}
	public String getCheckDate() {
		return checkDate;
	}
	public void setCheckDate(String checkDate) {
		this.checkDate = checkDate;
	}
	public String getReceiver() {
		return receiver;
	}
	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}
	public String getKind() {
		return kind;
	}
	public void setKind(String kind) {
		this.kind = kind;
	}
	public String getObjectCode() {
		return objectCode;
	}
	public void setObjectCode(String objectCode) {
		this.objectCode = objectCode;
	}
	
	
}
