package dto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EnrollLogInfoDTO.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class EnrollLogInfoDTO {
	private String objectCode;
	private String kind;
	private String content;
	private String date;
	private String memberCode;
	private int merge;
	public EnrollLogInfoDTO() {
	}
	public EnrollLogInfoDTO(String objectCode, String kind, String content,
			String date, String memberCode, int merge) {
		this.objectCode = objectCode;
		this.kind = kind;
		this.content = content;
		this.date = date;
		this.memberCode = memberCode;
		this.merge = merge;
	}
	public String getObjectCode() {
		return objectCode;
	}
	public void setObjectCode(String objectCode) {
		this.objectCode = objectCode;
	}
	public String getKind() {
		return kind;
	}
	public void setKind(String kind) {
		this.kind = kind;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	public String getMemberCode() {
		return memberCode;
	}
	public void setMemberCode(String memberCode) {
		this.memberCode = memberCode;
	}
	public int getMerge() {
		return merge;
	}
	public void setMerge(int merge) {
		this.merge = merge;
	}
	
}
