package dto;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EnrollTeamDTO.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public class EnrollTeamDTO {
	private String teamName;
	private String description;
	private String manager;
	private List<String> cooperatorList;
	private String tagList;
	public EnrollTeamDTO() {
	}
	public EnrollTeamDTO(String teamName, String description, String manager,
			List<String> cooperatorList, String tagList) {
		this.teamName = teamName;
		this.description = description;
		this.manager = manager;
		this.cooperatorList = cooperatorList;
		this.tagList = tagList;
	}
	public String getTeamName() {
		return teamName;
	}
	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getManager() {
		return manager;
	}
	public void setManager(String manager) {
		this.manager = manager;
	}
	public List<String> getCooperatorList() {
		return cooperatorList;
	}
	public void setCooperatorList(List<String> cooperatorList) {
		this.cooperatorList = cooperatorList;
	}
	public String getTagList() {
		return tagList;
	}
	public void setTagList(String tagList) {
		this.tagList = tagList;
	}
	
}
