package manager;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.util.List;

import model.CommitInfo;
import model.CopiedFile;
import model.OriginFile;
import model.OriginFileList;
import socialProExceptions.DAOException;
import socialProExceptions.FileException;
import socialProExceptions.FolderException;
import socialProExceptions.ProjectException;
import socialProExceptions.RemoteFileException;

import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.SftpException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileSearchable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface FileSearchable {
	
	public OriginFile justSearchOriginFileCode(String fileCode) throws DAOException, ParseException, FolderException, JSchException, IOException, SftpException;
	public OriginFile justSearchOriginFilePath(String filePath) throws DAOException, ParseException, FolderException, JSchException, IOException, SftpException;
	
	//searchOnlyCpFileContent
	public File searchFileCode(String fileCode) throws DAOException, ParseException, FolderException;
	public File searchFilePath(String filePath) throws DAOException, ParseException, FolderException;
	public File searchFileContentPath(String filePath) throws DAOException, ParseException, FolderException, FileNotFoundException, SftpException, IOException, JSchException;
	public File searchFileContentCode(String fileCode) throws DAOException, ParseException, FolderException, FileNotFoundException, SftpException, IOException, JSchException;
	public List<File> searchSiblingFileByPath(String filePath)throws DAOException, ParseException, FolderException;
	public List<File> searchSiblingFileByCode(String fileCode)throws DAOException, ParseException, FolderException;
	public List<File> searchFileByFolderPath(String folderPath)throws DAOException, ParseException, FolderException;
	public List<File> searchFileByFolderCode(String folderCode)throws DAOException, ParseException, FolderException;
	public List<File> searchAllFileByFPath(String folderPath) throws DAOException, ParseException, FolderException;
	public List<File> searchAllFileByFCode(String folderCode) throws DAOException, ParseException, FolderException;
	
	public List<File> searchFileAllByCpFolderCode(String cpFolderCode) throws DAOException, ParseException, FolderException;
	public List<File> searchFileAllByCpFolderPath(String cpFolderPath) throws DAOException, ParseException, FolderException;
	public OriginFileList searchAllFilesByOnlyOriginFCode(String oriFolderCode) throws DAOException, ParseException, FolderException;
	public OriginFileList searchAllFilesByOnlyOriginFPath(String oriFolderPath) throws DAOException, ParseException, FolderException;
	
	public OriginFile searchOnlyOriginFileCode(String fileCode)throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException, FolderException;
	public OriginFile searchOnlyOriginFilePath(String filePath) throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException, FolderException;		
	public OriginFile searchOnlyOriginFilePathContent(String filePath) throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException, FolderException;		
	
	//return only CopiedFile or Null
	public CopiedFile searchOnlyCpFileCode(String fileCode) throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException;
	public CopiedFile searchOnlyCpFilePath(String filePath) throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException;
	public CopiedFile searchOnlyCpFileContent(String filePath) throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException;
	
	public OriginFileList searchOnlyOriginFileByFolderPath(String oriFolderPath)throws DAOException, ParseException, FolderException;
	public OriginFileList searchOnlyOriginFileByFolderCode(String oriFolderCode)throws DAOException, ParseException, FolderException;	
	//return FileList for copiedFolder
	public List<File> searchOnlyCpFileByFolderPath(String cpFolderPath)throws DAOException, ParseException, FolderException;
	public List<File> searchOnlyCpFileByFolderCode(String cpFolderCode)throws DAOException, ParseException, FolderException;
	
	public boolean isCopiedFile(String filePath) throws DAOException,ParseException, FolderException, ProjectException, FileNotFoundException, SftpException, IOException, JSchException;
	public boolean isOriginFile(String filePath) throws DAOException,ParseException, FolderException, ProjectException,FileNotFoundException, SftpException, IOException, JSchException;
	
	public boolean checkFilePath(String filePath) throws DAOException, ParseException, FolderException;
	public boolean checkFileDiff(String fileCode, List<CommitInfo> commitInfoList) throws FileNotFoundException, DAOException, FileException, SftpException, IOException, JSchException, RemoteFileException, ParseException;
	
	/*public OriginFile searchFilePath(String path) throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException;
	public OriginFile searchFilePathForContent(String path) throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException;
	public CopiedFile searchCopiedFileContent(String path) throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException;
	//public OriginFile searchFileContent(String path) throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException;
	public OriginFile searchFileCode(String code)throws DAOException, ParseException, FileNotFoundException, SftpException, IOException, JSchException;
	public OriginFile searchFileAllByPath(String folderCode, String name)throws DAOException, ParseException;
	public OriginFileList searchFileAllByCode(String folderCode)throws DAOException, ParseException, FolderException;
	public CopiedFileList searchCopiedFileAllByCode(String folderCode)throws DAOException, ParseException, FolderException;
	public OriginFileList searchFileAllByPath(String folderPath)throws DAOException, ParseException, FolderException;
	public CopiedFileList searchCopiedFileAllByPath(String folderPath)throws DAOException, ParseException, FolderException;
	public OriginFileList searchFileAllByPathForCooper(String folderPath)throws DAOException, ParseException, FolderException;
	public String searchDiffFile(String ownerCode, String storageCode,String projectCode, String folderCode, String fileCode,String newContent,String commitTitle,String commitContent) throws FileNotFoundException, LoginException, DAOException, SftpException, IOException, JSchException, FileException, ParseException, RemoteFileException, CommitExcetion;
	public String searchDiffFile(String ownerCode, String storageCode,String projectCode, String folderCode, String fileCode,String newContent) throws FileNotFoundException, LoginException, DAOException, SftpException, IOException, JSchException, FileException, ParseException, RemoteFileException, CommitExcetion;
	public CopiedFile searchASelectCopiedFile(String path) throws DAOException,ParseException, FolderException, ProjectException, FileNotFoundException, SftpException, IOException, JSchException;
	public OriginFile searchASelectOriginFile(String path) throws DAOException,ParseException, FolderException, ProjectException,FileNotFoundException, SftpException, IOException, JSchException;
	
	*/
}
