package manager;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.util.List;
import java.util.Map;

import javax.security.auth.login.LoginException;

import model.CommitInfo;
import model.OriginFile;
import socialProExceptions.CommitExcetion;
import socialProExceptions.DAOException;
import socialProExceptions.FileException;
import socialProExceptions.FolderException;
import socialProExceptions.MemberException;
import socialProExceptions.ProjectException;
import socialProExceptions.RemoteFileException;
import socialProExceptions.TeamException;

import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.SftpException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileModifyable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface FileModifyable {
	public boolean modifyFileContent(String ownerCode, String storageCode,String projectCode,String folderCode,String fileCode, String newContent) throws FileNotFoundException, LoginException, DAOException, SftpException, IOException, JSchException, FileException, ParseException, RemoteFileException, FolderException, CommitExcetion, TeamException;
	public CommitInfo modifyFileContent(String ownerCode, String storageCode,String projectCode,String folderCode,String fileCode, String newContent,String commitTitle, String commitContent) throws FileNotFoundException, LoginException, DAOException, SftpException, IOException, JSchException, FileException, ParseException, RemoteFileException, CommitExcetion, FolderException, TeamException;
	/*public boolean modifyFileInfoName(String nickName, String code, String newName);
	public boolean modifyFileInfoPath(String nickName, String code, String newPath);
	public boolean modifyFileInfoAlterDate(String nickName, String code, GregorianCalendar newAlterDate);
	public boolean modifyFileInfoFCode(String nickName, String code, String newFolderCode);
	public boolean modifyFile(String nickName, String code, String newContent);*/
	public CommitInfo modifyFileContent(String ownerCode, String storageCode,String projectCode, String folderCode, String fileCode,String filePath, String newContent, String commitTitle,String commitContent) throws FileNotFoundException, LoginException,DAOException, SftpException, IOException, JSchException,FileException, ParseException, RemoteFileException, CommitExcetion,FolderException, TeamException;
	public boolean modifyFileContent(String ownerCode, String storageCode,String projectCode, String folderCode, String fileCode,String filePath, String newContent) throws FileNotFoundException,LoginException, DAOException, SftpException, IOException,JSchException, FileException, ParseException, RemoteFileException,FolderException, CommitExcetion, TeamException;
	
	public CommitInfo mergeFileContent(String ownerCode, String filePath, String newFileContent, String commitFileCode,String commiter, String commitCode, List<String> commitCodeList) throws FileNotFoundException, LoginException,DAOException, SftpException, IOException, JSchException,FileException, ParseException, RemoteFileException, CommitExcetion, TeamException, FolderException, MemberException, ProjectException;
	public Map<OriginFile, CommitInfo> mergeNewFileContent(String ownerCode, String folderPath, String newContent, String commitFileCode, String commiter, String commitCode, List<String> commitCodeList) throws FileNotFoundException, LoginException,DAOException, SftpException, IOException, JSchException,FileException, ParseException, RemoteFileException, CommitExcetion, TeamException, FolderException, MemberException, ProjectException;
	
}
