package manager;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileDetelable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface FileDetelable {
	/*public boolean deleteFileCode(String nickName, String code);
	public boolean deleteFilePath(String nickName, String path);*/
}
