package manager;

import java.text.ParseException;
import java.util.List;
import java.util.Map;

import model.CommitInfo;
import model.CopiedFolder;
import model.CopiedFolderList;
import model.OriginFolder;
import model.OriginFolderList;
import socialProExceptions.CommitExcetion;
import socialProExceptions.DAOException;
import socialProExceptions.FolderException;
import socialProExceptions.ProjectException;
import socialProExceptions.TeamException;

import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.SftpException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FolderCreatable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface FolderCreatable {
	
	public String insertOriginFolder(OriginFolder folder)throws DAOException, ParseException, SftpException, JSchException, CommitExcetion, FolderException;
	public List<String> insertOriginFolderList(OriginFolderList folderList)throws DAOException, ParseException, SftpException, JSchException, CommitExcetion, FolderException;
	
	public String insertCopiedFolder(CopiedFolder folder)throws DAOException, ParseException, SftpException, JSchException, CommitExcetion, FolderException;
	public List<String> insertCopiedFolderList(CopiedFolderList folderList)throws DAOException, ParseException, SftpException, JSchException, CommitExcetion, FolderException;
	
	public String createOriginFolder(String ownerCode,String ownerName, String name, String description, String path)throws DAOException, ParseException, SftpException, JSchException, FolderException;
	public OriginFolder createOriginFolderByPFCode(String ownerCode,String ownerName, String name, String description, String parentFolderCode)throws DAOException, ParseException, SftpException, JSchException, FolderException;
	
	public Map<String, CopiedFolder> createCopiedFolderByPFCode(String parentFolderPath,String ownerCode,String ownerName, String name, String description)throws DAOException, ParseException, SftpException, JSchException, FolderException, TeamException, ProjectException;
	public OriginFolder createOriginTeamCooperFolder(String parentFolderPath,String ownerCode,String ownerName, String name, String description)throws DAOException, ParseException, SftpException, JSchException, FolderException, TeamException, ProjectException;
		
	public String createFolder(String memberCode,String nickName, String name, String description, String path)throws DAOException, ParseException, SftpException, JSchException, FolderException;
	public String createFolder(String memberCode,String nickName, String name, String path) throws DAOException, ParseException, SftpException, JSchException, FolderException;
	public boolean insertCopiedFolder(List<CopiedFolder> cfList);

	public Map<OriginFolder,CommitInfo> copyFolder(String copyFolderCode, String commitCode, String commitorCode, String folderPath, String memberCode) throws DAOException, ParseException, FolderException, CommitExcetion, SftpException, JSchException;
}
