package manager;

import socialProExceptions.DAOException;
import socialProExceptions.MemberException;
import model.Member;
import model.MemberList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberSearchable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface MemberSearchable {
	public Member searchMemberNickName(String nickName)throws DAOException, MemberException;
	public Member searchMemberEmail(String email)throws DAOException, MemberException;
	public Member searchMemberEmail(String email,String pw)throws DAOException, MemberException;
	public Member searchMemberCode(String code) throws DAOException, MemberException;
}
