package manager;

import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.SftpException;

import socialProExceptions.DAOException;
import socialProExceptions.MemberException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberJoinable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface MemberJoinable {
	public String joinMember(String nickName, String email, String pw, String school, int entranceYear)throws DAOException, SftpException, JSchException, MemberException;
}
