package manager;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProjectSharable.java
//  @ Date : 2015-07-28
//  @ Author : 
//
//




public interface ProjectSharable {
	public boolean shareProjectCode(String nickName, String projectCode);
	public boolean shareProjectName(String nickName, String path);
}
