/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-12-20 01:45:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.realPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>AdminLTE 2 | Registration Page</title>\r\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\r\n");
      out.write("    <!-- Bootstrap 3.3.4 -->\r\n");
      out.write("    <link href=\"../../bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- Font Awesome Icons -->\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- Theme style -->\r\n");
      out.write("    <link href=\"../../dist/css/AdminLTE.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- iCheck -->\r\n");
      out.write("    <link href=\"../../plugins/iCheck/square/blue.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<!-- jQuery 2.1.4 -->\r\n");
      out.write("    <script src=\"../../plugins/jQuery/jQuery-2.1.4.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    //var infoModal = $('#myModal');\r\n");
      out.write("    \r\n");
      out.write("    function makeModalMsg() {\r\n");
      out.write("    \t$('input').iCheck({\r\n");
      out.write("            checkboxClass: 'icheckbox_square-blue',\r\n");
      out.write("            radioClass: 'iradio_square-blue',\r\n");
      out.write("            increaseArea: '20%' // optional\r\n");
      out.write("          });\r\n");
      out.write("    \t\r\n");
      out.write("        $('#register').bind('click', function(e){\r\n");
      out.write("        \te.preventDefault();\r\n");
      out.write("        \tvar input = this;\r\n");
      out.write("        \tinput.disabled = true;\r\n");
      out.write("        \tvar str=\"\";\r\n");
      out.write("        \t\r\n");
      out.write("        \tif ($(\"#nickName\").val().trim() == \"\") { alert(\"no\");str+=\"nickName,  \";}\r\n");
      out.write("        \tif ($(\"#email\").val().trim() == \"\") {str+=\"email,  \";}\r\n");
      out.write("\t   \t\tif ($(\"#pw\").val().trim() == \"\") {str+=\"pw,  \";}\r\n");
      out.write("\t   \t\tif ($(\"#school\").val().trim() == \"\") {str+=\"school,  \";}\r\n");
      out.write("\t   \t\tif ($(\"#entranceYear\").val().trim() == \"\") {str+=\"entranceYear \";} \r\n");
      out.write("        \t\r\n");
      out.write("        \tif(str!=\"\"){\r\n");
      out.write("        \t\tinput.disabled = false;\r\n");
      out.write("\t\t\t\tvar msg=$(\"#msg\");\r\n");
      out.write("\t\t\t\tmsg.text(str+\"을 입력해주세요\");\r\n");
      out.write("\t\t\t\tmsg.css(\"font-weight\",\"bold\");\r\n");
      out.write("\t\t\t\tmsg.css(\"font-size\",\"15px\");\r\n");
      out.write("\t\t\t\tmsg.css(\"color\",\"Tomato\");\r\n");
      out.write("\t\t\t\t$('#myModal').modal('show');\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t}\r\n");
      out.write("\r\n");
      out.write("        \tvar obj = new Object();\r\n");
      out.write("            obj.nickName = $(\"#nickName\").val();//\"BOBBY\";\r\n");
      out.write("            obj.email  = $(\"#email\").val();//\"BoBBY_@gamil.com\";\r\n");
      out.write("            obj.pw = $(\"#pw\").val();//\"pwpwBobby\";\r\n");
      out.write("            obj.school = $(\"#school\").val();//\"pwpwBobby\";\r\n");
      out.write("            obj.entranceYear = $(\"#entranceYear\").val();//\"pwpwBobby\";\r\n");
      out.write("            \r\n");
      out.write("            //alert(JSON.stringify(obj));\r\n");
      out.write("        \t\r\n");
      out.write("            /* ajax start */\r\n");
      out.write("        \t$.ajax({ \r\n");
      out.write("        \t\ttype : 'POST',\r\n");
      out.write("       \t\t\tdata : JSON.stringify(obj),\r\n");
      out.write("       \t\t\tcontentType : 'application/json;  charset=UTF-8',\r\n");
      out.write("       \t\t\turl : '../../signOn',\r\n");
      out.write("       \t\t\tdataType:'JSON',\r\n");
      out.write("       \t\t\tsuccess : function(a){\r\n");
      out.write("       \t\t\t\talert(\"여기는왜//.....제이슨이 오긴옴\");\r\n");
      out.write("       \t\t\t\tif(a.answer==\"success\"){\r\n");
      out.write("       \t\t\t\t\t\r\n");
      out.write("       \t\t\t\t\t$(\"#dynamicBtn\").css(\"visibility\",\"visible\");\r\n");
      out.write("       \t\t\t\t\t$(\"#closeBtn\").css(\"visibility\",\"hidden\");\r\n");
      out.write("          \t\t\t\t \r\n");
      out.write("       \t\t\t\t\tvar msg=$(\"#msg\");\r\n");
      out.write("       \t\t\t\t\tmsg.text(a.successMsg);\r\n");
      out.write("       \t\t\t\t\tmsg.css(\"font-weight\",\"bold\");\r\n");
      out.write("       \t\t\t\t\tmsg.css(\"font-size\",\"20px\");\r\n");
      out.write("       \t\t\t\t\tmsg.css(\"color\",\"SlateBlue\");\r\n");
      out.write("       \t\t\t\t\t    \r\n");
      out.write("       \t\t\t\t}\r\n");
      out.write("       \t\t\t\telse if(a.answer==\"fail\"){\r\n");
      out.write("\r\n");
      out.write("       \t\t\t\t\tinput.disabled = false;\r\n");
      out.write("       \t\t\t\t\tvar msg=$(\"#msg\");\r\n");
      out.write("       \t\t\t\t\tmsg.text(a.failMsg);\r\n");
      out.write("       \t\t\t\t\tmsg.css(\"font-weight\",\"bold\");\r\n");
      out.write("       \t\t\t\t\tmsg.css(\"font-size\",\"20px\");\r\n");
      out.write("       \t\t\t\t\tmsg.css(\"color\",\"Tomato\");\r\n");
      out.write("       \t\t\t\t}\r\n");
      out.write("       \t\t\t},\r\n");
      out.write("       \t\t\terror : function(e){\r\n");
      out.write("       \t\t\t\t//alert(\"에에에엥??? error\");\r\n");
      out.write("       \t\t\t},\r\n");
      out.write("       \t\t\tbeforeSend : function(){\r\n");
      out.write("       \t\t\t\t//alert(\"준비됐다..***.\");\r\n");
      out.write("       \t\t\t},\r\n");
      out.write("      \t\t\tcomplete : function(){\r\n");
      out.write("      \t\t\t\t//alert(\"이거되면 요청된거라는데...**..ㅠㅠ\");\r\n");
      out.write("      \t\t\t}\r\n");
      out.write("              \r\n");
      out.write("            });/* ajax end */\r\n");
      out.write("           \r\n");
      out.write("            $('#myModal').modal('show');\r\n");
      out.write("            \r\n");
      out.write("            return false;\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    $(function() {\r\n");
      out.write("    \tmakeModalMsg();\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write(" <body class=\"register-page\">\r\n");
      out.write("    <div class=\"register-box\">\r\n");
      out.write("      <div class=\"register-logo\">\r\n");
      out.write("        <a href=\"http://localhost:8089/socialPro/pages/realPage/SPWelcome.html\"><b>Admin</b>LTE</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"register-box-body\">\r\n");
      out.write("        <p class=\"login-box-msg\">Register a new membership</p>\r\n");
      out.write("        <form action=\"../../index.html\" method=\"post\">\r\n");
      out.write("          <div class=\"form-group has-feedback\">\r\n");
      out.write("            <input id=\"nickName\" type=\"text\" class=\"form-control\" placeholder=\"nick name\" required/>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-user form-control-feedback\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group has-feedback\">\r\n");
      out.write("            <input id=\"email\" type=\"email\" class=\"form-control\" placeholder=\"Email\" required/>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-envelope form-control-feedback\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group has-feedback\">\r\n");
      out.write("            <input id=\"pw\" type=\"password\" class=\"form-control\" placeholder=\"Password\" required/>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-lock form-control-feedback\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group has-feedback\">\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" placeholder=\"Retype password\" required/>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-log-in form-control-feedback\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group has-feedback\">\r\n");
      out.write("            <input id=\"school\" type=\"univercity\" class=\"form-control\" placeholder=\"school\" required/>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-log-in form-control-feedback\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group has-feedback\">\r\n");
      out.write("            <input id=\"entranceYear\" type=\"entranceYear\" class=\"form-control\" placeholder=\"Entrance Year\" required/>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-log-in form-control-feedback\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xs-8\">\r\n");
      out.write("              <div class=\"checkbox icheck\">\r\n");
      out.write("                <label>\r\n");
      out.write("                  <input type=\"checkbox\"> I agree to the <a href=\"#\">terms</a>\r\n");
      out.write("                </label>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div><!-- /.col -->\r\n");
      out.write("            <div class=\"col-xs-4\">\r\n");
      out.write("              <!-- <button id=\"register\" type=\"button\" class=\"btn btn-primary btn-block btn-flat\">Register</button> -->\r\n");
      out.write("              <button id=\"register\" type=\"button\" class=\"btn btn-primary btn-block btn-flat\" data-toggle=\"modal\" data-target=\"#myModal\">Register</button>\r\n");
      out.write("            </div><!-- /.col -->\r\n");
      out.write("            \r\n");
      out.write("            <!-- Modal -->\r\n");
      out.write("\t\t\t<div id=\"myModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t\t\t  <div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    <!-- Modal content-->\r\n");
      out.write("\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t\t        <button id=\"closeBtn\" type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t        <h4 class=\"modal-title\">Message</h4>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t\t        <p id=\"msg\">Some text in the modal.</p>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t      <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t      \t<a href=\"http://localhost:8089/socialPro/pages/realPage/SPWelcome.html\"><button id=\"dynamicBtn\" type=\"button\" class=\"btn btn-default\" style=\"visibility:hidden\">OK</button></a>\t\t\t        \r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"login.html\" class=\"text-center\">I already have a membership</a>\r\n");
      out.write("      </div><!-- /.form-box -->\r\n");
      out.write("    </div><!-- /.register-box -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap 3.3.2 JS -->\r\n");
      out.write("    <script src=\"../../bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- iCheck -->\r\n");
      out.write("    <script src=\"../../plugins/iCheck/icheck.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(function () {\r\n");
      out.write("        $('input').iCheck({\r\n");
      out.write("          checkboxClass: 'icheckbox_square-blue',\r\n");
      out.write("          radioClass: 'iradio_square-blue',\r\n");
      out.write("          increaseArea: '20%' // optional\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
